namespace Cinturon360.Shared.Models.Static.Organization;

/// <summary>
/// Static reference data for system time zones.
/// Record model is the source of truth.
/// Enum exists for legacy compatibility only.
/// </summary>
public static partial class SystemTimeZones
{
    // ------------------------------------------------------------------------
    // LEGACY ENUM (do NOT remove — used by existing aggregates, DB mappings)
    // ------------------------------------------------------------------------

    public enum SystemTimeZone : int
    {
        UTC = 0,

        Africa_Abidjan = 1001,
        Africa_Accra = 1002,
        Africa_Addis_Ababa = 1003,
        Africa_Algiers = 1004,
        Africa_Asmara = 1005,
        Africa_Bamako = 1006,
        Africa_Bangui = 1007,
        Africa_Banjul = 1008,
        Africa_Bissau = 1009,
        Africa_Blantyre = 1010,
        Africa_Brazzaville = 1011,
        Africa_Bujumbura = 1012,
        Africa_Cairo = 1013,
        Africa_Casablanca = 1014,
        Africa_Ceuta = 1015,
        Africa_Conakry = 1016,
        Africa_Dakar = 1017,
        Africa_Dar_es_Salaam = 1018,
        Africa_Djibouti = 1019,
        Africa_Douala = 1020,
        Africa_El_Aaiun = 1021,
        Africa_Freetown = 1022,
        Africa_Gaborone = 1023,
        Africa_Harare = 1024,
        Africa_Johannesburg = 1025,
        Africa_Juba = 1026,
        Africa_Kampala = 1027,
        Africa_Khartoum = 1028,
        Africa_Kigali = 1029,
        Africa_Kinshasa = 1030,
        Africa_Lagos = 1031,
        Africa_Libreville = 1032,
        Africa_Lome = 1033,
        Africa_Luanda = 1034,
        Africa_Lubumbashi = 1035,
        Africa_Lusaka = 1036,
        Africa_Malabo = 1037,
        Africa_Maputo = 1038,
        Africa_Maseru = 1039,
        Africa_Mbabane = 1040,
        Africa_Mogadishu = 1041,
        Africa_Monrovia = 1042,
        Africa_Nairobi = 1043,
        Africa_Ndjamena = 1044,
        Africa_Niamey = 1045,
        Africa_Nouakchott = 1046,
        Africa_Ouagadougou = 1047,
        Africa_Porto_Novo = 1048,
        Africa_Sao_Tome = 1049,
        Africa_Tripoli = 1050,
        Africa_Tunis = 1051,
        Africa_Windhoek = 1052,

        America_Adak = 2001,
        America_Anchorage = 2002,
        America_Anguilla = 2003,
        America_Antigua = 2004,
        America_Araguaina = 2005,
        America_Argentina_Buenos_Aires = 2006,
        America_Argentina_Catamarca = 2007,
        America_Argentina_Cordoba = 2008,
        America_Argentina_Jujuy = 2009,
        America_Argentina_La_Rioja = 2010,
        America_Argentina_Mendoza = 2011,
        America_Argentina_Rio_Gallegos = 2012,
        America_Argentina_Salta = 2013,
        America_Argentina_San_Juan = 2014,
        America_Argentina_San_Luis = 2015,
        America_Argentina_Tucuman = 2016,
        America_Argentina_Ushuaia = 2017,
        America_Aruba = 2018,
        America_Asuncion = 2019,
        America_Atikokan = 2020,
        America_Bahia = 2021,
        America_Bahia_Banderas = 2022,
        America_Barbados = 2023,
        America_Belem = 2024,
        America_Belize = 2025,
        America_Blanc_Sablon = 2026,
        America_Boa_Vista = 2027,
        America_Bogota = 2028,
        America_Boise = 2029,
        America_Cambridge_Bay = 2030,
        America_Campo_Grande = 2031,
        America_Cancun = 2032,
        America_Caracas = 2033,
        America_Cayenne = 2034,
        America_Cayman = 2035,
        America_Chicago = 2036,
        America_Chihuahua = 2037,
        America_Ciudad_Juarez = 2038,
        America_Costa_Rica = 2039,
        America_Coyhaique = 2040,
        America_Creston = 2041,
        America_Cuiaba = 2042,
        America_Curacao = 2043,
        America_Danmarkshavn = 2044,
        America_Dawson = 2045,
        America_Dawson_Creek = 2046,
        America_Denver = 2047,
        America_Detroit = 2048,
        America_Dominica = 2049,
        America_Edmonton = 2050,
        America_Eirunepe = 2051,
        America_El_Salvador = 2052,
        America_Fort_Nelson = 2053,
        America_Fortaleza = 2054,
        America_Glace_Bay = 2055,
        America_Goose_Bay = 2056,
        America_Grand_Turk = 2057,
        America_Grenada = 2058,
        America_Guadeloupe = 2059,
        America_Guatemala = 2060,
        America_Guayaquil = 2061,
        America_Guyana = 2062,
        America_Halifax = 2063,
        America_Havana = 2064,
        America_Hermosillo = 2065,
        America_Indiana_Indianapolis = 2066,
        America_Indiana_Knox = 2067,
        America_Indiana_Marengo = 2068,
        America_Indiana_Petersburg = 2069,
        America_Indiana_Tell_City = 2070,
        America_Indiana_Vevay = 2071,
        America_Indiana_Vincennes = 2072,
        America_Indiana_Winamac = 2073,
        America_Inuvik = 2074,
        America_Iqaluit = 2075,
        America_Jamaica = 2076,
        America_Juneau = 2077,
        America_Kentucky_Louisville = 2078,
        America_Kentucky_Monticello = 2079,
        America_Kralendijk = 2080,
        America_La_Paz = 2081,
        America_Lima = 2082,
        America_Los_Angeles = 2083,
        America_Lower_Princes = 2084,
        America_Maceio = 2085,
        America_Managua = 2086,
        America_Manaus = 2087,
        America_Marigot = 2088,
        America_Martinique = 2089,
        America_Matamoros = 2090,
        America_Mazatlan = 2091,
        America_Menominee = 2092,
        America_Merida = 2093,
        America_Metlakatla = 2094,
        America_Mexico_City = 2095,
        America_Miquelon = 2096,
        America_Moncton = 2097,
        America_Monterrey = 2098,
        America_Montevideo = 2099,
        America_Montserrat = 2100,
        America_Nassau = 2101,
        America_New_York = 2102,
        America_Nome = 2103,
        America_Noronha = 2104,
        America_North_Dakota_Beulah = 2105,
        America_North_Dakota_Center = 2106,
        America_North_Dakota_New_Salem = 2107,
        America_Nuuk = 2108,
        America_Ojinaga = 2109,
        America_Panama = 2110,
        America_Paramaribo = 2111,
        America_Phoenix = 2112,
        America_Port_au_Prince = 2113,
        America_Port_of_Spain = 2114,
        America_Porto_Velho = 2115,
        America_Puerto_Rico = 2116,
        America_Punta_Arenas = 2117,
        America_Rankin_Inlet = 2118,
        America_Recife = 2119,
        America_Regina = 2120,
        America_Resolute = 2121,
        America_Rio_Branco = 2122,
        America_Santarem = 2123,
        America_Santiago = 2124,
        America_Santo_Domingo = 2125,
        America_Sao_Paulo = 2126,
        America_Scoresbysund = 2127,
        America_Sitka = 2128,
        America_St_Barthelemy = 2129,
        America_St_Johns = 2130,
        America_St_Kitts = 2131,
        America_St_Lucia = 2132,
        America_St_Thomas = 2133,
        America_St_Vincent = 2134,
        America_Swift_Current = 2135,
        America_Tegucigalpa = 2136,
        America_Thule = 2137,
        America_Tijuana = 2138,
        America_Toronto = 2139,
        America_Tortola = 2140,
        America_Vancouver = 2141,
        America_Whitehorse = 2142,
        America_Winnipeg = 2143,
        America_Yakutat = 2144,

        Antarctica_Casey = 3001,
        Antarctica_Davis = 3002,
        Antarctica_DumontDUrville = 3003,
        Antarctica_Macquarie = 3004,
        Antarctica_Mawson = 3005,
        Antarctica_McMurdo = 3006,
        Antarctica_Palmer = 3007,
        Antarctica_Rothera = 3008,
        Antarctica_Syowa = 3009,
        Antarctica_Troll = 3010,
        Antarctica_Vostok = 3011,

        Arctic_Longyearbyen = 4001,

        Asia_Aden = 5001,
        Asia_Almaty = 5002,
        Asia_Amman = 5003,
        Asia_Anadyr = 5004,
        Asia_Aqtau = 5005,
        Asia_Aqtobe = 5006,
        Asia_Ashgabat = 5007,
        Asia_Atyrau = 5008,
        Asia_Baghdad = 5009,
        Asia_Bahrain = 5010,
        Asia_Baku = 5011,
        Asia_Bangkok = 5012,
        Asia_Barnaul = 5013,
        Asia_Beirut = 5014,
        Asia_Bishkek = 5015,
        Asia_Brunei = 5016,
        Asia_Chita = 5017,
        Asia_Colombo = 5018,
        Asia_Damascus = 5019,
        Asia_Dhaka = 5020,
        Asia_Dili = 5021,
        Asia_Dubai = 5022,
        Asia_Dushanbe = 5023,
        Asia_Famagusta = 5024,
        Asia_Gaza = 5025,
        Asia_Hebron = 5026,
        Asia_Ho_Chi_Minh = 5027,
        Asia_Hong_Kong = 5028,
        Asia_Hovd = 5029,
        Asia_Irkutsk = 5030,
        Asia_Jakarta = 5031,
        Asia_Jayapura = 5032,
        Asia_Jerusalem = 5033,
        Asia_Kabul = 5034,
        Asia_Kamchatka = 5035,
        Asia_Karachi = 5036,
        Asia_Kathmandu = 5037,
        Asia_Khandyga = 5038,
        Asia_Kolkata = 5039,
        Asia_Krasnoyarsk = 5040,
        Asia_Kuala_Lumpur = 5041,
        Asia_Kuching = 5042,
        Asia_Kuwait = 5043,
        Asia_Macau = 5044,
        Asia_Magadan = 5045,
        Asia_Makassar = 5046,
        Asia_Manila = 5047,
        Asia_Muscat = 5048,
        Asia_Nicosia = 5049,
        Asia_Novokuznetsk = 5050,
        Asia_Novosibirsk = 5051,
        Asia_Omsk = 5052,
        Asia_Oral = 5053,
        Asia_Phnom_Penh = 5054,
        Asia_Pontianak = 5055,
        Asia_Pyongyang = 5056,
        Asia_Qatar = 5057,
        Asia_Qostanay = 5058,
        Asia_Qyzylorda = 5059,
        Asia_Riyadh = 5060,
        Asia_Sakhalin = 5061,
        Asia_Samarkand = 5062,
        Asia_Seoul = 5063,
        Asia_Shanghai = 5064,
        Asia_Singapore = 5065,
        Asia_Srednekolymsk = 5066,
        Asia_Taipei = 5067,
        Asia_Tashkent = 5068,
        Asia_Tbilisi = 5069,
        Asia_Tehran = 5070,
        Asia_Thimphu = 5071,
        Asia_Tokyo = 5072,
        Asia_Tomsk = 5073,
        Asia_Ulaanbaatar = 5074,
        Asia_Urumqi = 5075,
        Asia_Ust_Nera = 5076,
        Asia_Vientiane = 5077,
        Asia_Vladivostok = 5078,
        Asia_Yakutsk = 5079,
        Asia_Yangon = 5080,
        Asia_Yekaterinburg = 5081,
        Asia_Yerevan = 5082,

        Atlantic_Azores = 6001,
        Atlantic_Bermuda = 6002,
        Atlantic_Canary = 6003,
        Atlantic_Cape_Verde = 6004,
        Atlantic_Faroe = 6005,
        Atlantic_Madeira = 6006,
        Atlantic_Reykjavik = 6007,
        Atlantic_South_Georgia = 6008,
        Atlantic_St_Helena = 6009,
        Atlantic_Stanley = 6010,

        Australia_Adelaide = 7001,
        Australia_Brisbane = 7002,
        Australia_Broken_Hill = 7003,
        Australia_Darwin = 7004,
        Australia_Eucla = 7005,
        Australia_Hobart = 7006,
        Australia_Lindeman = 7007,
        Australia_Lord_Howe = 7008,
        Australia_Melbourne = 7009,
        Australia_Perth = 7010,
        Australia_Sydney = 7011,

        Europe_Amsterdam = 8001,
        Europe_Andorra = 8002,
        Europe_Astrakhan = 8003,
        Europe_Athens = 8004,
        Europe_Belgrade = 8005,
        Europe_Berlin = 8006,
        Europe_Bratislava = 8007,
        Europe_Brussels = 8008,
        Europe_Bucharest = 8009,
        Europe_Budapest = 8010,
        Europe_Busingen = 8011,
        Europe_Chisinau = 8012,
        Europe_Copenhagen = 8013,
        Europe_Dublin = 8014,
        Europe_Gibraltar = 8015,
        Europe_Guernsey = 8016,
        Europe_Helsinki = 8017,
        Europe_Isle_of_Man = 8018,
        Europe_Istanbul = 8019,
        Europe_Jersey = 8020,
        Europe_Kaliningrad = 8021,
        Europe_Kirov = 8022,
        Europe_Kyiv = 8023,
        Europe_Lisbon = 8024,
        Europe_Ljubljana = 8025,
        Europe_London = 8026,
        Europe_Luxembourg = 8027,
        Europe_Madrid = 8028,
        Europe_Malta = 8029,
        Europe_Mariehamn = 8030,
        Europe_Minsk = 8031,
        Europe_Monaco = 8032,
        Europe_Moscow = 8033,
        Europe_Oslo = 8034,
        Europe_Paris = 8035,
        Europe_Podgorica = 8036,
        Europe_Prague = 8037,
        Europe_Riga = 8038,
        Europe_Rome = 8039,
        Europe_Samara = 8040,
        Europe_San_Marino = 8041,
        Europe_Sarajevo = 8042,
        Europe_Saratov = 8043,
        Europe_Simferopol = 8044,
        Europe_Skopje = 8045,
        Europe_Sofia = 8046,
        Europe_Stockholm = 8047,
        Europe_Tallinn = 8048,
        Europe_Tirane = 8049,
        Europe_Ulyanovsk = 8050,
        Europe_Vaduz = 8051,
        Europe_Vatican = 8052,
        Europe_Vienna = 8053,
        Europe_Vilnius = 8054,
        Europe_Volgograd = 8055,
        Europe_Warsaw = 8056,
        Europe_Zagreb = 8057,
        Europe_Zurich = 8058,

        Indian_Antananarivo = 9001,
        Indian_Chagos = 9002,
        Indian_Christmas = 9003,
        Indian_Cocos = 9004,
        Indian_Comoro = 9005,
        Indian_Kerguelen = 9006,
        Indian_Mahe = 9007,
        Indian_Maldives = 9008,
        Indian_Mauritius = 9009,
        Indian_Mayotte = 9010,
        Indian_Reunion = 9011,

        Pacific_Apia = 10001,
        Pacific_Auckland = 10002,
        Pacific_Bougainville = 10003,
        Pacific_Chatham = 10004,
        Pacific_Chuuk = 10005,
        Pacific_Easter = 10006,
        Pacific_Efate = 10007,
        Pacific_Fakaofo = 10008,
        Pacific_Fiji = 10009,
        Pacific_Funafuti = 10010,
        Pacific_Galapagos = 10011,
        Pacific_Gambier = 10012,
        Pacific_Guadalcanal = 10013,
        Pacific_Guam = 10014,
        Pacific_Honolulu = 10015,
        Pacific_Kanton = 10016,
        Pacific_Kiritimati = 10017,
        Pacific_Kosrae = 10018,
        Pacific_Kwajalein = 10019,
        Pacific_Majuro = 10020,
        Pacific_Marquesas = 10021,
        Pacific_Midway = 10022,
        Pacific_Nauru = 10023,
        Pacific_Niue = 10024,
        Pacific_Norfolk = 10025,
        Pacific_Noumea = 10026,
        Pacific_Pago_Pago = 10027,
        Pacific_Palau = 10028,
        Pacific_Pitcairn = 10029,
        Pacific_Pohnpei = 10030,
        Pacific_Port_Moresby = 10031,
        Pacific_Rarotonga = 10032,
        Pacific_Saipan = 10033,
        Pacific_Tahiti = 10034,
        Pacific_Tarawa = 10035,
        Pacific_Tongatapu = 10036,
        Pacific_Wake = 10037,
        Pacific_Wallis = 10038,
    }

    // ------------------------------------------------------------------------
    // RECORD MODEL (source of truth)
    // ------------------------------------------------------------------------

    public sealed record SystemTimeZoneInfo(
        int Id,
        string Code,
        string CodeLower,
        string IanaId,
        string DisplayName,
        string StandardName,
        string DaylightName,
        TimeSpan BaseUtcOffset,
        bool SupportsDaylightSavingTime
    )
    {
        public SystemTimeZone Enum =>
            (SystemTimeZone)Id;
    }

    // ------------------------------------------------------------------------
    // SYSTEM SOURCE
    // ------------------------------------------------------------------------

    private static readonly IReadOnlyDictionary<string, TimeZoneInfo> _system =
        TimeZoneInfo
            .GetSystemTimeZones()
            .ToDictionary(x => x.Id, StringComparer.OrdinalIgnoreCase);

    private static SystemTimeZoneInfo Create(
        int id,
        string ianaId)
    {
        var tz = _system.TryGetValue(ianaId, out var found)
            ? found
            : TimeZoneInfo.Utc;

        return new SystemTimeZoneInfo(
            id,
            ianaId.Replace("/", "_").ToUpperInvariant(),
            ianaId.Replace("/", "_").ToLowerInvariant(),
            tz.Id,
            tz.DisplayName,
            tz.StandardName,
            tz.DaylightName,
            tz.BaseUtcOffset,
            tz.SupportsDaylightSavingTime);
    }

    // ------------------------------------------------------------------------
    // SINGLE SOURCE OF TRUTH
    // ------------------------------------------------------------------------

    private static readonly IReadOnlyList<SystemTimeZoneInfo> _all =
    [
        Create(0, "UTC"),

        Create(1001, "Africa/Abidjan"),
        Create(1002, "Africa/Accra"),
        Create(1003, "Africa/Addis_Ababa"),
        Create(1004, "Africa/Algiers"),
        Create(1005, "Africa/Asmara"),
        Create(1006, "Africa/Bamako"),
        Create(1007, "Africa/Bangui"),
        Create(1008, "Africa/Banjul"),
        Create(1009, "Africa/Bissau"),
        Create(1010, "Africa/Blantyre"),
        Create(1011, "Africa/Brazzaville"),
        Create(1012, "Africa/Bujumbura"),
        Create(1013, "Africa/Cairo"),
        Create(1014, "Africa/Casablanca"),
        Create(1015, "Africa/Ceuta"),
        Create(1016, "Africa/Conakry"),
        Create(1017, "Africa/Dakar"),
        Create(1018, "Africa/Dar_es_Salaam"),
        Create(1019, "Africa/Djibouti"),
        Create(1020, "Africa/Douala"),
        Create(1021, "Africa/El_Aaiun"),
        Create(1022, "Africa/Freetown"),
        Create(1023, "Africa/Gaborone"),
        Create(1024, "Africa/Harare"),
        Create(1025, "Africa/Johannesburg"),
        Create(1026, "Africa/Juba"),
        Create(1027, "Africa/Kampala"),
        Create(1028, "Africa/Khartoum"),
        Create(1029, "Africa/Kigali"),
        Create(1030, "Africa/Kinshasa"),
        Create(1031, "Africa/Lagos"),
        Create(1032, "Africa/Libreville"),
        Create(1033, "Africa/Lome"),
        Create(1034, "Africa/Luanda"),
        Create(1035, "Africa/Lubumbashi"),
        Create(1036, "Africa/Lusaka"),
        Create(1037, "Africa/Malabo"),
        Create(1038, "Africa/Maputo"),
        Create(1039, "Africa/Maseru"),
        Create(1040, "Africa/Mbabane"),
        Create(1041, "Africa/Mogadishu"),
        Create(1042, "Africa/Monrovia"),
        Create(1043, "Africa/Nairobi"),
        Create(1044, "Africa/Ndjamena"),
        Create(1045, "Africa/Niamey"),
        Create(1046, "Africa/Nouakchott"),
        Create(1047, "Africa/Ouagadougou"),
        Create(1048, "Africa/Porto-Novo"),
        Create(1049, "Africa/Sao_Tome"),
        Create(1050, "Africa/Tripoli"),
        Create(1051, "Africa/Tunis"),
        Create(1052, "Africa/Windhoek"),

        Create(2001, "America/Adak"),
        Create(2002, "America/Anchorage"),
        Create(2003, "America/Anguilla"),
        Create(2004, "America/Antigua"),
        Create(2005, "America/Araguaina"),
        Create(2006, "America/Argentina/Buenos_Aires"),
        Create(2007, "America/Argentina/Catamarca"),
        Create(2008, "America/Argentina/Cordoba"),
        Create(2009, "America/Argentina/Jujuy"),
        Create(2010, "America/Argentina/La_Rioja"),
        Create(2011, "America/Argentina/Mendoza"),
        Create(2012, "America/Argentina/Rio_Gallegos"),
        Create(2013, "America/Argentina/Salta"),
        Create(2014, "America/Argentina/San_Juan"),
        Create(2015, "America/Argentina/San_Luis"),
        Create(2016, "America/Argentina/Tucuman"),
        Create(2017, "America/Argentina/Ushuaia"),
        Create(2018, "America/Aruba"),
        Create(2019, "America/Asuncion"),
        Create(2020, "America/Atikokan"),
        Create(2021, "America/Bahia"),
        Create(2022, "America/Bahia_Banderas"),
        Create(2023, "America/Barbados"),
        Create(2024, "America/Belem"),
        Create(2025, "America/Belize"),
        Create(2026, "America/Blanc-Sablon"),
        Create(2027, "America/Boa_Vista"),
        Create(2028, "America/Bogota"),
        Create(2029, "America/Boise"),
        Create(2030, "America/Cambridge_Bay"),
        Create(2031, "America/Campo_Grande"),
        Create(2032, "America/Cancun"),
        Create(2033, "America/Caracas"),
        Create(2034, "America/Cayenne"),
        Create(2035, "America/Cayman"),
        Create(2036, "America/Chicago"),
        Create(2037, "America/Chihuahua"),
        Create(2038, "America/Ciudad_Juarez"),
        Create(2039, "America/Costa_Rica"),
        Create(2040, "America/Coyhaique"),
        Create(2041, "America/Creston"),
        Create(2042, "America/Cuiaba"),
        Create(2043, "America/Curacao"),
        Create(2044, "America/Danmarkshavn"),
        Create(2045, "America/Dawson"),
        Create(2046, "America/Dawson_Creek"),
        Create(2047, "America/Denver"),
        Create(2048, "America/Detroit"),
        Create(2049, "America/Dominica"),
        Create(2050, "America/Edmonton"),
        Create(2051, "America/Eirunepe"),
        Create(2052, "America/El_Salvador"),
        Create(2053, "America/Fort_Nelson"),
        Create(2054, "America/Fortaleza"),
        Create(2055, "America/Glace_Bay"),
        Create(2056, "America/Goose_Bay"),
        Create(2057, "America/Grand_Turk"),
        Create(2058, "America/Grenada"),
        Create(2059, "America/Guadeloupe"),
        Create(2060, "America/Guatemala"),
        Create(2061, "America/Guayaquil"),
        Create(2062, "America/Guyana"),
        Create(2063, "America/Halifax"),
        Create(2064, "America/Havana"),
        Create(2065, "America/Hermosillo"),
        Create(2066, "America/Indiana/Indianapolis"),
        Create(2067, "America/Indiana/Knox"),
        Create(2068, "America/Indiana/Marengo"),
        Create(2069, "America/Indiana/Petersburg"),
        Create(2070, "America/Indiana/Tell_City"),
        Create(2071, "America/Indiana/Vevay"),
        Create(2072, "America/Indiana/Vincennes"),
        Create(2073, "America/Indiana/Winamac"),
        Create(2074, "America/Inuvik"),
        Create(2075, "America/Iqaluit"),
        Create(2076, "America/Jamaica"),
        Create(2077, "America/Juneau"),
        Create(2078, "America/Kentucky/Louisville"),
        Create(2079, "America/Kentucky/Monticello"),
        Create(2080, "America/Kralendijk"),
        Create(2081, "America/La_Paz"),
        Create(2082, "America/Lima"),
        Create(2083, "America/Los_Angeles"),
        Create(2084, "America/Lower_Princes"),
        Create(2085, "America/Maceio"),
        Create(2086, "America/Managua"),
        Create(2087, "America/Manaus"),
        Create(2088, "America/Marigot"),
        Create(2089, "America/Martinique"),
        Create(2090, "America/Matamoros"),
        Create(2091, "America/Mazatlan"),
        Create(2092, "America/Menominee"),
        Create(2093, "America/Merida"),
        Create(2094, "America/Metlakatla"),
        Create(2095, "America/Mexico_City"),
        Create(2096, "America/Miquelon"),
        Create(2097, "America/Moncton"),
        Create(2098, "America/Monterrey"),
        Create(2099, "America/Montevideo"),
        Create(2100, "America/Montserrat"),
        Create(2101, "America/Nassau"),
        Create(2102, "America/New_York"),
        Create(2103, "America/Nome"),
        Create(2104, "America/Noronha"),
        Create(2105, "America/North_Dakota/Beulah"),
        Create(2106, "America/North_Dakota/Center"),
        Create(2107, "America/North_Dakota/New_Salem"),
        Create(2108, "America/Nuuk"),
        Create(2109, "America/Ojinaga"),
        Create(2110, "America/Panama"),
        Create(2111, "America/Paramaribo"),
        Create(2112, "America/Phoenix"),
        Create(2113, "America/Port-au-Prince"),
        Create(2114, "America/Port_of_Spain"),
        Create(2115, "America/Porto_Velho"),
        Create(2116, "America/Puerto_Rico"),
        Create(2117, "America/Punta_Arenas"),
        Create(2118, "America/Rankin_Inlet"),
        Create(2119, "America/Recife"),
        Create(2120, "America/Regina"),
        Create(2121, "America/Resolute"),
        Create(2122, "America/Rio_Branco"),
        Create(2123, "America/Santarem"),
        Create(2124, "America/Santiago"),
        Create(2125, "America/Santo_Domingo"),
        Create(2126, "America/Sao_Paulo"),
        Create(2127, "America/Scoresbysund"),
        Create(2128, "America/Sitka"),
        Create(2129, "America/St_Barthelemy"),
        Create(2130, "America/St_Johns"),
        Create(2131, "America/St_Kitts"),
        Create(2132, "America/St_Lucia"),
        Create(2133, "America/St_Thomas"),
        Create(2134, "America/St_Vincent"),
        Create(2135, "America/Swift_Current"),
        Create(2136, "America/Tegucigalpa"),
        Create(2137, "America/Thule"),
        Create(2138, "America/Tijuana"),
        Create(2139, "America/Toronto"),
        Create(2140, "America/Tortola"),
        Create(2141, "America/Vancouver"),
        Create(2142, "America/Whitehorse"),
        Create(2143, "America/Winnipeg"),
        Create(2144, "America/Yakutat"),

        Create(3001, "Antarctica/Casey"),
        Create(3002, "Antarctica/Davis"),
        Create(3003, "Antarctica/DumontDUrville"),
        Create(3004, "Antarctica/Macquarie"),
        Create(3005, "Antarctica/Mawson"),
        Create(3006, "Antarctica/McMurdo"),
        Create(3007, "Antarctica/Palmer"),
        Create(3008, "Antarctica/Rothera"),
        Create(3009, "Antarctica/Syowa"),
        Create(3010, "Antarctica/Troll"),
        Create(3011, "Antarctica/Vostok"),

        Create(4001, "Arctic/Longyearbyen"),

        Create(5001, "Asia/Aden"),
        Create(5002, "Asia/Almaty"),
        Create(5003, "Asia/Amman"),
        Create(5004, "Asia/Anadyr"),
        Create(5005, "Asia/Aqtau"),
        Create(5006, "Asia/Aqtobe"),
        Create(5007, "Asia/Ashgabat"),
        Create(5008, "Asia/Atyrau"),
        Create(5009, "Asia/Baghdad"),
        Create(5010, "Asia/Bahrain"),
        Create(5011, "Asia/Baku"),
        Create(5012, "Asia/Bangkok"),
        Create(5013, "Asia/Barnaul"),
        Create(5014, "Asia/Beirut"),
        Create(5015, "Asia/Bishkek"),
        Create(5016, "Asia/Brunei"),
        Create(5017, "Asia/Chita"),
        Create(5018, "Asia/Colombo"),
        Create(5019, "Asia/Damascus"),
        Create(5020, "Asia/Dhaka"),
        Create(5021, "Asia/Dili"),
        Create(5022, "Asia/Dubai"),
        Create(5023, "Asia/Dushanbe"),
        Create(5024, "Asia/Famagusta"),
        Create(5025, "Asia/Gaza"),
        Create(5026, "Asia/Hebron"),
        Create(5027, "Asia/Ho_Chi_Minh"),
        Create(5028, "Asia/Hong_Kong"),
        Create(5029, "Asia/Hovd"),
        Create(5030, "Asia/Irkutsk"),
        Create(5031, "Asia/Jakarta"),
        Create(5032, "Asia/Jayapura"),
        Create(5033, "Asia/Jerusalem"),
        Create(5034, "Asia/Kabul"),
        Create(5035, "Asia/Kamchatka"),
        Create(5036, "Asia/Karachi"),
        Create(5037, "Asia/Kathmandu"),
        Create(5038, "Asia/Khandyga"),
        Create(5039, "Asia/Kolkata"),
        Create(5040, "Asia/Krasnoyarsk"),
        Create(5041, "Asia/Kuala_Lumpur"),
        Create(5042, "Asia/Kuching"),
        Create(5043, "Asia/Kuwait"),
        Create(5044, "Asia/Macau"),
        Create(5045, "Asia/Magadan"),
        Create(5046, "Asia/Makassar"),
        Create(5047, "Asia/Manila"),
        Create(5048, "Asia/Muscat"),
        Create(5049, "Asia/Nicosia"),
        Create(5050, "Asia/Novokuznetsk"),
        Create(5051, "Asia/Novosibirsk"),
        Create(5052, "Asia/Omsk"),
        Create(5053, "Asia/Oral"),
        Create(5054, "Asia/Phnom_Penh"),
        Create(5055, "Asia/Pontianak"),
        Create(5056, "Asia/Pyongyang"),
        Create(5057, "Asia/Qatar"),
        Create(5058, "Asia/Qostanay"),
        Create(5059, "Asia/Qyzylorda"),
        Create(5060, "Asia/Riyadh"),
        Create(5061, "Asia/Sakhalin"),
        Create(5062, "Asia/Samarkand"),
        Create(5063, "Asia/Seoul"),
        Create(5064, "Asia/Shanghai"),
        Create(5065, "Asia/Singapore"),
        Create(5066, "Asia/Srednekolymsk"),
        Create(5067, "Asia/Taipei"),
        Create(5068, "Asia/Tashkent"),
        Create(5069, "Asia/Tbilisi"),
        Create(5070, "Asia/Tehran"),
        Create(5071, "Asia/Thimphu"),
        Create(5072, "Asia/Tokyo"),
        Create(5073, "Asia/Tomsk"),
        Create(5074, "Asia/Ulaanbaatar"),
        Create(5075, "Asia/Urumqi"),
        Create(5076, "Asia/Ust-Nera"),
        Create(5077, "Asia/Vientiane"),
        Create(5078, "Asia/Vladivostok"),
        Create(5079, "Asia/Yakutsk"),
        Create(5080, "Asia/Yangon"),
        Create(5081, "Asia/Yekaterinburg"),
        Create(5082, "Asia/Yerevan"),

        Create(6001, "Atlantic/Azores"),
        Create(6002, "Atlantic/Bermuda"),
        Create(6003, "Atlantic/Canary"),
        Create(6004, "Atlantic/Cape_Verde"),
        Create(6005, "Atlantic/Faroe"),
        Create(6006, "Atlantic/Madeira"),
        Create(6007, "Atlantic/Reykjavik"),
        Create(6008, "Atlantic/South_Georgia"),
        Create(6009, "Atlantic/St_Helena"),
        Create(6010, "Atlantic/Stanley"),

        Create(7001, "Australia/Adelaide"),
        Create(7002, "Australia/Brisbane"),
        Create(7003, "Australia/Broken_Hill"),
        Create(7004, "Australia/Darwin"),
        Create(7005, "Australia/Eucla"),
        Create(7006, "Australia/Hobart"),
        Create(7007, "Australia/Lindeman"),
        Create(7008, "Australia/Lord_Howe"),
        Create(7009, "Australia/Melbourne"),
        Create(7010, "Australia/Perth"),
        Create(7011, "Australia/Sydney"),

        Create(8001, "Europe/Amsterdam"),
        Create(8002, "Europe/Andorra"),
        Create(8003, "Europe/Astrakhan"),
        Create(8004, "Europe/Athens"),
        Create(8005, "Europe/Belgrade"),
        Create(8006, "Europe/Berlin"),
        Create(8007, "Europe/Bratislava"),
        Create(8008, "Europe/Brussels"),
        Create(8009, "Europe/Bucharest"),
        Create(8010, "Europe/Budapest"),
        Create(8011, "Europe/Busingen"),
        Create(8012, "Europe/Chisinau"),
        Create(8013, "Europe/Copenhagen"),
        Create(8014, "Europe/Dublin"),
        Create(8015, "Europe/Gibraltar"),
        Create(8016, "Europe/Guernsey"),
        Create(8017, "Europe/Helsinki"),
        Create(8018, "Europe/Isle_of_Man"),
        Create(8019, "Europe/Istanbul"),
        Create(8020, "Europe/Jersey"),
        Create(8021, "Europe/Kaliningrad"),
        Create(8022, "Europe/Kirov"),
        Create(8023, "Europe/Kyiv"),
        Create(8024, "Europe/Lisbon"),
        Create(8025, "Europe/Ljubljana"),
        Create(8026, "Europe/London"),
        Create(8027, "Europe/Luxembourg"),
        Create(8028, "Europe/Madrid"),
        Create(8029, "Europe/Malta"),
        Create(8030, "Europe/Mariehamn"),
        Create(8031, "Europe/Minsk"),
        Create(8032, "Europe/Monaco"),
        Create(8033, "Europe/Moscow"),
        Create(8034, "Europe/Oslo"),
        Create(8035, "Europe/Paris"),
        Create(8036, "Europe/Podgorica"),
        Create(8037, "Europe/Prague"),
        Create(8038, "Europe/Riga"),
        Create(8039, "Europe/Rome"),
        Create(8040, "Europe/Samara"),
        Create(8041, "Europe/San_Marino"),
        Create(8042, "Europe/Sarajevo"),
        Create(8043, "Europe/Saratov"),
        Create(8044, "Europe/Simferopol"),
        Create(8045, "Europe/Skopje"),
        Create(8046, "Europe/Sofia"),
        Create(8047, "Europe/Stockholm"),
        Create(8048, "Europe/Tallinn"),
        Create(8049, "Europe/Tirane"),
        Create(8050, "Europe/Ulyanovsk"),
        Create(8051, "Europe/Vaduz"),
        Create(8052, "Europe/Vatican"),
        Create(8053, "Europe/Vienna"),
        Create(8054, "Europe/Vilnius"),
        Create(8055, "Europe/Volgograd"),
        Create(8056, "Europe/Warsaw"),
        Create(8057, "Europe/Zagreb"),
        Create(8058, "Europe/Zurich"),

        Create(9001, "Indian/Antananarivo"),
        Create(9002, "Indian/Chagos"),
        Create(9003, "Indian/Christmas"),
        Create(9004, "Indian/Cocos"),
        Create(9005, "Indian/Comoro"),
        Create(9006, "Indian/Kerguelen"),
        Create(9007, "Indian/Mahe"),
        Create(9008, "Indian/Maldives"),
        Create(9009, "Indian/Mauritius"),
        Create(9010, "Indian/Mayotte"),
        Create(9011, "Indian/Reunion"),

        Create(10001, "Pacific/Apia"),
        Create(10002, "Pacific/Auckland"),
        Create(10003, "Pacific/Bougainville"),
        Create(10004, "Pacific/Chatham"),
        Create(10005, "Pacific/Chuuk"),
        Create(10006, "Pacific/Easter"),
        Create(10007, "Pacific/Efate"),
        Create(10008, "Pacific/Fakaofo"),
        Create(10009, "Pacific/Fiji"),
        Create(10010, "Pacific/Funafuti"),
        Create(10011, "Pacific/Galapagos"),
        Create(10012, "Pacific/Gambier"),
        Create(10013, "Pacific/Guadalcanal"),
        Create(10014, "Pacific/Guam"),
        Create(10015, "Pacific/Honolulu"),
        Create(10016, "Pacific/Kanton"),
        Create(10017, "Pacific/Kiritimati"),
        Create(10018, "Pacific/Kosrae"),
        Create(10019, "Pacific/Kwajalein"),
        Create(10020, "Pacific/Majuro"),
        Create(10021, "Pacific/Marquesas"),
        Create(10022, "Pacific/Midway"),
        Create(10023, "Pacific/Nauru"),
        Create(10024, "Pacific/Niue"),
        Create(10025, "Pacific/Norfolk"),
        Create(10026, "Pacific/Noumea"),
        Create(10027, "Pacific/Pago_Pago"),
        Create(10028, "Pacific/Palau"),
        Create(10029, "Pacific/Pitcairn"),
        Create(10030, "Pacific/Pohnpei"),
        Create(10031, "Pacific/Port_Moresby"),
        Create(10032, "Pacific/Rarotonga"),
        Create(10033, "Pacific/Saipan"),
        Create(10034, "Pacific/Tahiti"),
        Create(10035, "Pacific/Tarawa"),
        Create(10036, "Pacific/Tongatapu"),
        Create(10037, "Pacific/Wake"),
        Create(10038, "Pacific/Wallis"),
    ];

    public static IReadOnlyList<SystemTimeZoneInfo> All => _all;

    // ------------------------------------------------------------------------
    // INDEXES (O(1) lookups)
    // ------------------------------------------------------------------------

    private static readonly IReadOnlyDictionary<int, SystemTimeZoneInfo> _byId =
        _all.ToDictionary(x => x.Id);

    private static readonly IReadOnlyDictionary<string, SystemTimeZoneInfo> _byIanaId =
        _all.ToDictionary(x => x.IanaId, StringComparer.OrdinalIgnoreCase);

    // ------------------------------------------------------------------------
    // LOOKUPS
    // ------------------------------------------------------------------------

    public static SystemTimeZoneInfo Get(SystemTimeZone type)
        => Get((int)type);

    public static SystemTimeZoneInfo Get(int id)
        => _byId[id];

    public static SystemTimeZoneInfo? TryGet(int id)
        => _byId.TryGetValue(id, out var value) ? value : null;

    public static SystemTimeZoneInfo GetByIanaId(string ianaId)
        => _byIanaId[ianaId];

    public static SystemTimeZoneInfo? TryGetByIanaId(string ianaId)
        => _byIanaId.TryGetValue(ianaId, out var value) ? value : null;

    public static SystemTimeZone ToEnum(int id)
        => (SystemTimeZone)id;

    public static int ToId(SystemTimeZone type)
        => (int)type;

    // ------------------------------------------------------------------------
    // STRONGLY TYPED ACCESSORS
    // ------------------------------------------------------------------------

    public static SystemTimeZoneInfo UTC => Get(SystemTimeZone.UTC);

    public static SystemTimeZoneInfo AustraliaSydney => Get(SystemTimeZone.Australia_Sydney);

    public static SystemTimeZoneInfo EuropeLondon => Get(SystemTimeZone.Europe_London);

    public static SystemTimeZoneInfo AmericaNewYork => Get(SystemTimeZone.America_New_York);

    public static SystemTimeZoneInfo AsiaSingapore => Get(SystemTimeZone.Asia_Singapore);

    // ------------------------------------------------------------------------
    // UI PROJECTION
    // ------------------------------------------------------------------------

    public static IReadOnlyList<(SystemTimeZone Type, string Name)> DropdownOptions =>
        _all
            .Select(x => ((SystemTimeZone)x.Id, $"{x.IanaId} ({x.BaseUtcOffset:hh\\:mm})"))
            .ToList();
}